function [Dates,AllCom,NonFuel,FoodAndBeverage,Food,Beverage,Industrial,AgriculturalRawMaterials,Metals,FuelEnergy,CrudeOil,Aluminum,Bananas,BarleyCanadian,Beef,Coal,CocoaBeans,CoffeeArabicas,CoffeeRobusta,RapeseedOil,Copper,Cotton,FishmealPeru,Groundnuts,HidesHeavy,ChinaImport,Lamb,Lead,SoftLogs,HardLogs,MaizeCorn,NaturalGasRussian,NaturalGasIndonesian,NaturalGasLouisiana,Nickel,CrudeOilAvg,CrudeOilUK,OilDubai,CrudeOilInt,OliveOil,Oranges,PalmOil,SwinePork,PoultryChicken,Rice,Rubber,FishSalmon,HardSawnwood,SoftSawnwood,Shrimp,SoybeanMeal,SoybeanOil,SoybeansUS,SugarEuro,SugarFreeMarket,SugarUS,SunflowerOil,TeaMombasa,Tin,Uranium,Wheat,WoolCoarse,WoolFine,Zinc] = importfile1(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   IMPORTFILE1(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   importfile1('project2Data.xls','ExternalData',[1,3,5],[1,3,426]);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2015/03/13 23:40:16

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = [1,3,5];
    endRow = [1,3,426];
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:BL%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:BL%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64]);

%% Allocate imported array to column variable names
Dates = cellVectors(:,1);
AllCom = cellVectors(:,2);
NonFuel = cellVectors(:,3);
FoodAndBeverage = cellVectors(:,4);
Food = cellVectors(:,5);
Beverage = cellVectors(:,6);
Industrial = cellVectors(:,7);
AgriculturalRawMaterials = cellVectors(:,8);
Metals = cellVectors(:,9);
FuelEnergy = cellVectors(:,10);
CrudeOil = cellVectors(:,11);
Aluminum = cellVectors(:,12);
Bananas = cellVectors(:,13);
BarleyCanadian = cellVectors(:,14);
Beef = cellVectors(:,15);
Coal = cellVectors(:,16);
CocoaBeans = cellVectors(:,17);
CoffeeArabicas = cellVectors(:,18);
CoffeeRobusta = cellVectors(:,19);
RapeseedOil = cellVectors(:,20);
Copper = cellVectors(:,21);
Cotton = cellVectors(:,22);
FishmealPeru = cellVectors(:,23);
Groundnuts = cellVectors(:,24);
HidesHeavy = cellVectors(:,25);
ChinaImport = cellVectors(:,26);
Lamb = cellVectors(:,27);
Lead = cellVectors(:,28);
SoftLogs = cellVectors(:,29);
HardLogs = cellVectors(:,30);
MaizeCorn = cellVectors(:,31);
NaturalGasRussian = cellVectors(:,32);
NaturalGasIndonesian = cellVectors(:,33);
NaturalGasLouisiana = cellVectors(:,34);
Nickel = cellVectors(:,35);
CrudeOilAvg = cellVectors(:,36);
CrudeOilUK = cellVectors(:,37);
OilDubai = cellVectors(:,38);
CrudeOilInt = cellVectors(:,39);
OliveOil = cellVectors(:,40);
Oranges = cellVectors(:,41);
PalmOil = cellVectors(:,42);
SwinePork = cellVectors(:,43);
PoultryChicken = cellVectors(:,44);
Rice = cellVectors(:,45);
Rubber = cellVectors(:,46);
FishSalmon = cellVectors(:,47);
HardSawnwood = cellVectors(:,48);
SoftSawnwood = cellVectors(:,49);
Shrimp = cellVectors(:,50);
SoybeanMeal = cellVectors(:,51);
SoybeanOil = cellVectors(:,52);
SoybeansUS = cellVectors(:,53);
SugarEuro = cellVectors(:,54);
SugarFreeMarket = cellVectors(:,55);
SugarUS = cellVectors(:,56);
SunflowerOil = cellVectors(:,57);
TeaMombasa = cellVectors(:,58);
Tin = cellVectors(:,59);
Uranium = cellVectors(:,60);
Wheat = cellVectors(:,61);
WoolCoarse = cellVectors(:,62);
WoolFine = cellVectors(:,63);
Zinc = cellVectors(:,64);

